insert into Produtos(nome,preco) values('p1',1.99);
insert into Produtos(nome,preco) values('p2',2.5);
insert into Produtos(nome,preco) values('p3',3.99);
insert into Produtos(nome,preco) values('p5',6.5);
insert into Produtos(nome,preco) values('p4',15.99);
insert into Produtos(nome,preco) values('p7',28.5);
insert into Produtos(nome,preco) values('t9',6.99);
insert into Produtos(nome,preco) values('551.2',2.45);
insert into Produtos(nome,preco) values('pucrs',1.39);
insert into Produtos(nome,preco) values('mae do fred',0.01);